### ISSUE TITLE
Add Instance claim

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#18]
Extend CoMID to carry per-instance claims (e.g., serial numbers, IMEIs, etc.)

**Comment by nedmsmith** [comment]
claims-entry = {
? ref-claims => reference-value / [2* reference-value],
? end-claims => endorsed-value / [2* endorsed-value],
 ? inst-claims => instance-claim-entry,
* $$claims-entry-extension,
}
instance-claim-entry = {
  element-name,
  instance-values =>  instance-value / [2* instance-value], 
}
instance-value => instance-value-type,
instance-value-type /= bstr ; are there other well defined types under #6.4711 or EAT etc...

**Comment by thomas-fossati** [comment]
Have a look into [this](https://tools.ietf.org/html/draft-ietf-cbor-tags-oid-04)

**Comment by nedmsmith** [comment]
Fixed in #38
