### ISSUE TITLE
Patch and upgrade relations for CoMID

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#20]
If we want to support SW lifecycle for embedded firmware, we need to model the common cases of update and patch.  Similar to (Co)SWID we need to be able to say things like: _"MyFW 1.1.0 is an update of MyFW 1.0.0"_ or _"YourFW 1.0.1 is a patch of YourFW 1.0.0"_ without having to make assumptions on the versioning scheme in use, i.e., by means of an explicit type relation.

**Comment by nedmsmith** [comment]
We have defined 'supersedes' relationship type. This gives 'update' semantics. 
We were hoping to avoid the complexity of patch semantics - I think in part by being able to point to coswid. Does it work to say that if FW is patchable that the mfg'r should use coswid instead of comid?

**Comment by nedmsmith** [comment]
‘includes’
The current module has additional module(s) identified by the linked tag(s). The union of all modules describes an acceptable ‘device’.
‘or-includes’
The current module has additional module(s) identified by the linked tag(s) that describe alternative acceptable modules. At least one of the alternatives is included to describe an acceptable ‘device’.
‘supplements’
The current module has additional claims that augment the claim set of the target module. The current tag module information must match the target module for the claims to be combined under the target.
‘updates’
The current module contains claims that fully replace the target module claims. This is applied when the module is updated or changes in some fashion. 
‘replaces’
The current tag contains corrections to a previously issued tag. This tag replaces the target tag. The tag-id remains unchanged. The tag-version is incremented.
‘patches’
The current module contains claims that partially replace the target module claims. This is applied when the module is updated or changes in some fashion. The target module contains both valid and replaced claims.

**Comment by thomas-fossati** [comment]
We should also say which relations are intra CoMID and which has CoMID->CoSWID semantics.

In particular, we need at least one CoMID->CoSWID relationship from the top-level CoMID (AKA "the device") to the the various SW packages that are expected to run on it.  And/or the other way around: we possibly need to extend CoSWID to add a new relation that has CoMID->CoSWID only semantics and says that a certain SW package runs on a certain module / device.
