### ISSUE TITLE
An Explicit type for CoMIDs

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#21]
Should we define a type qualifier to distinguish between Class, Instance and Identity CoMIDs?

Introducing a bit of rigidity in to the type system will make some things impossible (e.g., mixing Instance and Identity claims in the same CoMID), however it will give us some advantages:
* Reduce cognitive dissonance;
* Improve link semantics;
* Limit attack surface;
* Reduce implementation complexity.

**Comment by nedmsmith** [comment]
Would it be possible to see an example of the type structure?
I'm concerned that typing would require multiple corims (and therefore unnecessary signing/verify operations).
If the typing applies only to tags (comid and coswid) then the result will be an increase in tags and increase in number of links (linked-tags). 
The semantics of linking needs to be revisited to make sure we're on the same page.
Current semantics: 
(1) multiple tags in the same or different corim are not required to be semantically related.
(2) claims in the same tag (claims-entry) means all claims are extant for the module (module-type). i.e. verifier accepts all asserted claims as being relevant to evidence that matches any one of the measurements found in extant claims.

Linked-tags under 'parent' or 'supplemental' follows the semantics for (2). 
Linked-tags under 'supersedes' has different semantics from (2) in that extant claims are replaced by superseded claims. 

If we have strong typing for the type of claim in addition to the above linked-tags relationships (essentially overloading relationship semantics with tag type semantics, then it isn't clear how both goals are met with the same relationship code point. We would have to add another field to link-type that is the tag-type IMO.
e.g.
linked-tags-entry = {
  tag-id => $tag-id-type,
  tag-rel => $tag-rel-type,
  ? tag-thumbprint => hash-entry, ; digest of the CBOR encoding of the concise-tag
  ? tag-issuer => tag-issuer-type,
  **? tag-type => $tag-type-type, ; choice: reference, endorsement, identity, instance**
}

**Comment by thomas-fossati** [comment]
> Would it be possible to see an example of the type structure?

(sketch quality alert!) at the top level I'm thinking of something like the following:
```
concise-mid-tag = {
  tag-id,
  module-info,
  claims,
  linked-tags,
  * $$extns,
}
```
where `claims` is a choice between three different types:
```
claims //= ( class => [ class-entry ] )
claims //= ( instance => [ instance-entry ] )
claims //= ( identity => [ identity-entry ] )

class = -1
instance = -2
identity = -3

class-entry = {
  ; TODO class claims
}

instance-entry = {
  ; TODO instance claims
}

identity-entry = {
  ; TODO identity claims
}
```

> I'm concerned that typing would require multiple corims (and therefore unnecessary signing/verify operations).

no, one could stash any number of CoMIDs (of any type) inside the same CoRIM.  So there would be only one signature, if so desired.

**Comment by henkbirkholz** [comment]
This issues seems to be addressed by the advanced layout of environment-map and triples-map work now.
-01 wil still lack expositional text on how environment-maps are used in the four type of records in triples-map, though. That is an essential part of the semantics, but unfortunately pushed to -02

**Comment by thomas-fossati** [comment]
Triples have made this is OBE
