### ISSUE TITLE
entity-entry is coswid specific

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats/draft-birkholz-rats-corim#27]
cohmid use for link-entry expects or presumes it should carry roles that are are specific to cohmids, hence it does NOT address the role of ModuleCreator. Shall we have our own role or modify / extend the existing roles? 

Ned: This is similar discussion to $rel / $relationships in link-entry. If it is problematic extending the $role namespace then we need to define a different namespece that is specific to cohmid. But that implies defining a cohmid specific entity-entry structure (I think) or possibly extending the coswid entity-entry structure with a cohmid specific role attribute e.g. $cohmid-role. 

Yogesh: My preference would be to simply extend the $role namespace in CoSwid documentation. Lets attempt to keep all the possible roles in one namespace be it ModuleCreator or possibly new roles coming in future (like tagIntegrator, specific to entity responsible for CoRiM Manifest creation).

This keeps the role concept centrally located for future evolution and helps assigning multiple roles to an entity. Any differing views are Welcome!

**Comment by nedmsmith** [comment]
PR #53 closes this issue.
