### ISSUE TITLE
identity claims should allow element-name matching

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/draft-birkholz-rats-corim#44]
Currently, comid uses element-name for matching endorsed-value, reference-value and instance-value claims. However, identity claims use 'device ID'. This asymmetry means it isn't possible to associate a deviceID with a module or element. We intuitively rely on a credential (e.g. certificate) to make this association where the Subject Name or other certificate fields encodes the element-name information that the certificate binds to the deviceID value and key material. 
In a DICE certificate, the element (TCB) is described with tcb-info which contains the element-name. The other fields contain the deviceID and key material. 
A more exact match would be possible if the Endorsement manifest included both pieces of information (element-name and deviceID/key material)

**Comment by nedmsmith** [comment]
There are two types of identity for a module. One is a cryptographic identity which we've modeled as identity-value and non-cryptographic identifiers we've currently modeled as instance-value which is a choice. I think this is the correct way to model cryptographic and non-cryptographic module identities. However, there may be a use case for returning arbitrary instance data with a manifest that possibly could be used as an identifier (or tracking number) but isn't the value used to identify / track the asset. Therefore, it make sense to have a bag of instance claims. Since we can have an array of instance-claims the array essentially is a bag of instance claims. But it isn't clear which is to be used to identify / track the module. In other words does it make sense to have a 'non-cryptographic-identity' that is an $$instance-claim-choice? (maybe this is over thinking)

We might want to reflect the semantics that the current 'identity-value' is a 'cryptographic-identity'. 

As a style consideration, should the four types of claims use a more descriptive '-claim' rather than '-value' as the suffix? The claim consists of an key-value pair (which is element-name, element-value for the most part). So technically the bounding map is a claim.

**Comment by nedmsmith** [comment]
Taking a closer look at identity-value map there isn't an extension point for it. I think it is reasonable that W3C DID will be a device ID type that relies on zero-knowledge proofs rather than keys. We don't need to include DID right now, but given a properly defined extension point, it could be added. Since there is an array of identity-claims it would be possible to have a bag of identities some key based some DID based etc.

**Comment by thomas-fossati** [comment]
> Taking a closer look at identity-value map there isn't an extension point for it. I think it is reasonable that W3C DID will be a device ID type that relies on zero-knowledge proofs rather than keys. We don't need to include DID right now, but given a properly defined extension point, it could be added. Since there is an array of identity-claims it would be possible to have a bag of identities some key based some DID based etc.

I agree with your assessment.  We could extend `$device-id-type` to accept values of type `uri` or, if we want to be more precise, a `did-uri` (i.e., a CDDL uri with the right regex constraint)

**Comment by nedmsmith** [comment]
Are you thinking the DID URL is sufficient or should it describe a DID Document? The DID spec says: "Each DID document can express cryptographic material, verification methods, or services, which provide a set of mechanisms enabling a DID controller to prove control of the DID." I'm thinking the manifest claims should contain the cryptographic material (which I presume includes the ZKP ingredients).

**Comment by thomas-fossati** [comment]
Maybe I am misunderstanding the DID concept altogether, but I thought the whole thing was about decoupling the identity proof (DID document) from the identity itself (the URI pointing to the DID document).  By pulling in the entire DID document in the Identity claim it seems to me that we'd be going counter the DID principle?  (That said, I may be completely off, I probably need to re-read the DID spec.)

**Comment by nedmsmith** [comment]
Resolution: module-metadata will change so that it has only 'element-name' and 'module-version' and an extension point.
module-metadata-type = {
  ? 0 => element-name,
  ? 1 => module-version,
  * $$module-metadata-extension
}

**Comment by nedmsmith** [comment]
PR #52 addresses this issue
