### ISSUE TITLE
ip-addrs-key doesn't need to be one-or-more

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/draft-birkholz-rats-corim#60]
Since there can be one-or-more instance-claims if there are multiple ip addresses then each address, whether ipv4 or ipv6 can be selected from the instance-claim-choice. Just need to add each as a choice. 

e.g. 
```
$$instance_claim {
  0 : ip4-addr-type (bytes .size 4)
  1 : ip6-addr-type (bytes .size 6)
  2 : serial-number-type (text)
  3 : ueid-type (ueid)
  4 : uuid-type (uuid)
  5 : mac-addr-type (bytes .size 6)
}
```

**Comment by thomas-fossati** [comment]
It looked to me like a low-hanging optimisation that was worth grabbing.  I think having dual stack connectivity might be a pretty common case.  With your suggestion, if you want to add both IPv4 and IPv6 addresses you'd have to duplicate the element-name.
