### ISSUE TITLE
Register `module-creator` in the Entity Role Values Registry

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#61]
Add text in the draft to register the `module-creator` codepoint in the Software Tag Entity Role Values Registry.

_Originally posted by @thomas-fossati in https://github.com/ietf-rats/draft-birkholz-rats-corim/pull/53#r599476572_

**Comment by henkbirkholz** [comment]
Addressed by inclusion of

`$comid-role-type-choice` /= comid.creator`

in entity-map.
