### ISSUE TITLE
What is a "tagged integer"?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#87]
Provide a description of a "tagged integer", in particular what purposes it serves.

Also, consider maybe a more evocative name.

**Comment by nedmsmith** [comment]
It is used in connection with $class-id-type-choice /= tagged-int-type where vendor ID is required. It can be used in cases where there are a small number of object classes and limited storage for larger class IDs such as OID and UUID.
